### Spring properties
# Service registers under this name
spring:
  application:
    name: service2
  datasource:
    url: jdbc:mysql://localhost:3307/student?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 3333

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false