### Spring properties
# Service registers under this name
spring:
  application:
    name: apiGateway
  main:
    web-application-type: reactive
##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
      ## service1
      - id: service1
        uri: lb://service1
        predicates:
        - Path=/service1/**
      ## Service2     
      - id: service2
        uri: lb://service2
        predicates:
        - Path=/service2/**
        
# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
# HTTP Server (Tomcat) Port
server:
  port: 8088
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false